# Generated by Django 4.2.2 on 2023-06-09 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Incomplete', max_length=20)),
            ],
        ),
    ]
